package install.sinapse;

public class Circuito {
	private String CIRCUITO_NOMBRE;
	private int CIRCUITO_NUMERO;
	private String CIRCUITO_TIPO;
	private boolean CIRCUITO_TELEGESTIONADO;
	private String CIRCUITO_TIPO_CONDUCTOR;
	private String CIRCUITO_SECCION_CONDUCTOR;
	private String CIRCUITO_TIPO_CANALIZACION;
	
	public String getCIRCUITO_NOMBRE() {
		return CIRCUITO_NOMBRE;
	}

	public void setCIRCUITO_NOMBRE(String cIRCUITO_NOMBRE) {
		CIRCUITO_NOMBRE = cIRCUITO_NOMBRE;
	}

	public int getCIRCUITO_NUMERO() {
		return CIRCUITO_NUMERO;
	}

	public void setCIRCUITO_NUMERO(int cIRCUITO_NUMERO) {
		CIRCUITO_NUMERO = cIRCUITO_NUMERO;
	}

	public String getCIRCUITO_TIPO() {
		return CIRCUITO_TIPO;
	}

	public void setCIRCUITO_TIPO(String cIRCUITO_TIPO) {
		CIRCUITO_TIPO = cIRCUITO_TIPO;
	}

	public boolean isCIRCUITO_TELEGESTIONADO() {
		return CIRCUITO_TELEGESTIONADO;
	}

	public void setCIRCUITO_TELEGESTIONADO(boolean cIRCUITO_TELEGESTIONADO) {
		CIRCUITO_TELEGESTIONADO = cIRCUITO_TELEGESTIONADO;
	}

	public String getCIRCUITO_TIPO_CONDUCTOR() {
		return CIRCUITO_TIPO_CONDUCTOR;
	}

	public void setCIRCUITO_TIPO_CONDUCTOR(String cIRCUITO_TIPO_CONDUCTOR) {
		CIRCUITO_TIPO_CONDUCTOR = cIRCUITO_TIPO_CONDUCTOR;
	}

	public String getCIRCUITO_SECCION_CONDUCTOR() {
		return CIRCUITO_SECCION_CONDUCTOR;
	}

	public void setCIRCUITO_SECCION_CONDUCTOR(String cIRCUITO_SECCION_CONDUCTOR) {
		CIRCUITO_SECCION_CONDUCTOR = cIRCUITO_SECCION_CONDUCTOR;
	}

	public String getCIRCUITO_TIPO_CANALIZACION() {
		return CIRCUITO_TIPO_CANALIZACION;
	}

	public void setCIRCUITO_TIPO_CANALIZACION(String cIRCUITO_TIPO_CANALIZACION) {
		CIRCUITO_TIPO_CANALIZACION = cIRCUITO_TIPO_CANALIZACION;
	}

	public Circuito(String nom,int num,String tip,boolean tele,String tipCond,String secCond,String cana)
	{
		CIRCUITO_NOMBRE=nom;
		CIRCUITO_NUMERO=num;
		CIRCUITO_TIPO=tip;
		CIRCUITO_TELEGESTIONADO=tele;
		CIRCUITO_TIPO_CONDUCTOR=tipCond;
		CIRCUITO_SECCION_CONDUCTOR=secCond;
		CIRCUITO_TIPO_CANALIZACION=cana;
	}
}
